create table if not exists public.profiles (
  user_id uuid primary key references auth.users (id) on delete cascade,
  role text not null check (role in ('shopper', 'seller')),
  username text not null check (length(btrim(username)) >= 2),
  shop_name text,
  phone text,
  delivery_address text,
  location text,
  profile_image_path text,
  store_banner_path text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profiles_role_details_check check (
    (
      role = 'seller'
      and length(btrim(shop_name)) >= 2
      and phone is null
      and delivery_address is null
    )
    or (
      role = 'shopper'
      and shop_name is null
      and nullif(btrim(phone), '') is not null
      and delivery_address is not null
      and length(btrim(delivery_address)) >= 5
    )
  )
);

alter table public.profiles enable row level security;

revoke all on public.profiles from anon, authenticated;
grant select on public.profiles to authenticated;
grant update (
  username,
  shop_name,
  phone,
  delivery_address,
  location,
  profile_image_path,
  store_banner_path,
  updated_at
) on public.profiles to authenticated;

drop policy if exists "Users can read their own profile" on public.profiles;
create policy "Users can read their own profile"
  on public.profiles for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "Users can update their own profile" on public.profiles;
create policy "Users can update their own profile"
  on public.profiles for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create or replace function public.create_marketplace_profile()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  profile_role text;
  account_username text;
begin
  profile_role := case
    when new.raw_user_meta_data ->> 'role' = 'seller' then 'seller'
    else 'shopper'
  end;
  account_username := coalesce(
    case
      when length(trim(new.raw_user_meta_data ->> 'username')) >= 2
        then trim(new.raw_user_meta_data ->> 'username')
    end,
    case
      when length(split_part(new.email, '@', 1)) >= 2
        then split_part(new.email, '@', 1)
    end,
    'Marketplace user'
  );

  insert into public.profiles (
    user_id,
    role,
    username,
    shop_name,
    phone,
    delivery_address
  )
  values (
    new.id,
    profile_role,
    account_username,
    nullif(trim(new.raw_user_meta_data ->> 'shop_name'), ''),
    nullif(trim(new.raw_user_meta_data ->> 'phone'), ''),
    nullif(trim(new.raw_user_meta_data ->> 'delivery_address'), '')
  )
  on conflict (user_id) do nothing;
  return new;
end;
$$;

revoke all on function public.create_marketplace_profile() from public, anon, authenticated;

drop trigger if exists on_marketplace_auth_user_created on auth.users;
create trigger on_marketplace_auth_user_created
  after insert on auth.users
  for each row execute function public.create_marketplace_profile();

create or replace function public.set_marketplace_profile_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists set_marketplace_profile_updated_at on public.profiles;
create trigger set_marketplace_profile_updated_at
  before update on public.profiles
  for each row execute function public.set_marketplace_profile_updated_at();

create table if not exists public.marketplace_listings (
  id bigint generated by default as identity (start with 1000) primary key,
  seller_id uuid not null references public.profiles (user_id) on delete cascade,
  seller_name text not null check (length(btrim(seller_name)) >= 2),
  category text not null,
  subcategory text not null,
  name text not null check (length(btrim(name)) between 2 and 120),
  description text not null check (length(btrim(description)) between 10 and 3000),
  price numeric(10, 2) not null check (price > 0 and price <= 10000000),
  image_path text not null,
  condition text not null check (condition in ('Brand new', 'Like new', 'Very good', 'Good')),
  size text,
  quantity integer not null default 1 check (quantity between 0 and 10000),
  status text not null default 'draft' check (status in ('draft', 'active', 'sold', 'archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint marketplace_listings_size_check check (
    category <> 'thrift' or nullif(btrim(size), '') is not null
  ),
  constraint marketplace_listings_image_owner_check check (
    image_path like seller_id::text || '/%'
  ),
  constraint marketplace_listings_active_stock_check check (
    status <> 'active' or quantity > 0
  )
);

create index if not exists marketplace_listings_public_browse_idx
  on public.marketplace_listings (category, subcategory, created_at desc)
  where status = 'active' and quantity > 0;
create index if not exists marketplace_listings_seller_idx
  on public.marketplace_listings (seller_id, created_at desc);

alter table public.marketplace_listings enable row level security;

revoke all on public.marketplace_listings from anon, authenticated;
grant select on public.marketplace_listings to anon, authenticated;
grant insert, update, delete on public.marketplace_listings to authenticated;
grant usage, select on sequence public.marketplace_listings_id_seq to authenticated;

drop trigger if exists set_marketplace_listing_updated_at on public.marketplace_listings;
create trigger set_marketplace_listing_updated_at
  before update on public.marketplace_listings
  for each row execute function public.set_marketplace_profile_updated_at();

drop policy if exists "Anyone can view available marketplace listings" on public.marketplace_listings;
create policy "Anyone can view available marketplace listings"
  on public.marketplace_listings for select
  to anon, authenticated
  using (
    (status = 'active' and quantity > 0)
    or seller_id = (select auth.uid())
  );

drop policy if exists "Sellers can create their own listings" on public.marketplace_listings;
create policy "Sellers can create their own listings"
  on public.marketplace_listings for insert
  to authenticated
  with check (
    seller_id = (select auth.uid())
    and exists (
      select 1 from public.profiles
      where user_id = (select auth.uid()) and role = 'seller'
    )
  );

drop policy if exists "Sellers can update their own listings" on public.marketplace_listings;
create policy "Sellers can update their own listings"
  on public.marketplace_listings for update
  to authenticated
  using (
    seller_id = (select auth.uid())
    and exists (
      select 1 from public.profiles
      where user_id = (select auth.uid()) and role = 'seller'
    )
  )
  with check (
    seller_id = (select auth.uid())
    and exists (
      select 1 from public.profiles
      where user_id = (select auth.uid()) and role = 'seller'
    )
  );

drop policy if exists "Sellers can delete their own listings" on public.marketplace_listings;
create policy "Sellers can delete their own listings"
  on public.marketplace_listings for delete
  to authenticated
  using (
    seller_id = (select auth.uid())
    and exists (
      select 1 from public.profiles
      where user_id = (select auth.uid()) and role = 'seller'
    )
  );

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'profile-media',
  'profile-media',
  false,
  8388608,
  array['image/jpeg', 'image/png', 'image/webp', 'image/avif']
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
    'listing-media',
    'listing-media',
    true,
    5242880,
    array['image/jpeg', 'image/png', 'image/webp', 'image/avif']
)
on conflict (id) do update
set public = excluded.public,
      file_size_limit = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Anyone can read marketplace listing images" on storage.objects;
create policy "Anyone can read marketplace listing images"
    on storage.objects for select
    to public
    using (bucket_id = 'listing-media');

drop policy if exists "Sellers can upload their own listing images" on storage.objects;
create policy "Sellers can upload their own listing images"
    on storage.objects for insert
    to authenticated
    with check (
      bucket_id = 'listing-media'
      and (storage.foldername(name))[1] = (select auth.uid())::text
      and exists (
        select 1 from public.profiles
        where user_id = (select auth.uid()) and role = 'seller'
      )
    );

drop policy if exists "Sellers can update their own listing images" on storage.objects;
create policy "Sellers can update their own listing images"
    on storage.objects for update
    to authenticated
    using (
      bucket_id = 'listing-media'
      and (storage.foldername(name))[1] = (select auth.uid())::text
    )
    with check (
      bucket_id = 'listing-media'
      and (storage.foldername(name))[1] = (select auth.uid())::text
      and exists (
        select 1 from public.profiles
        where user_id = (select auth.uid()) and role = 'seller'
      )
    );

drop policy if exists "Sellers can delete their own listing images" on storage.objects;
create policy "Sellers can delete their own listing images"
    on storage.objects for delete
    to authenticated
    using (
      bucket_id = 'listing-media'
      and (storage.foldername(name))[1] = (select auth.uid())::text
      and exists (
        select 1 from public.profiles
        where user_id = (select auth.uid()) and role = 'seller'
      )
    );

drop policy if exists "Users can read their own profile media" on storage.objects;
create policy "Users can read their own profile media"
  on storage.objects for select
  to authenticated
  using (
    bucket_id = 'profile-media'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

drop policy if exists "Users can upload their own profile media" on storage.objects;
create policy "Users can upload their own profile media"
  on storage.objects for insert
  to authenticated
  with check (
    bucket_id = 'profile-media'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

drop policy if exists "Users can update their own profile media" on storage.objects;
create policy "Users can update their own profile media"
  on storage.objects for update
  to authenticated
  using (
    bucket_id = 'profile-media'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  )
  with check (
    bucket_id = 'profile-media'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

drop policy if exists "Users can delete their own profile media" on storage.objects;
create policy "Users can delete their own profile media"
  on storage.objects for delete
  to authenticated
  using (
    bucket_id = 'profile-media'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );
